sudo: required
services:
  - docker

before_install:
  - docker build -t kannan1985/netapp_docker_demo -f Dockerfile.dev .

script:
  - docker run kannan1985/netapp_docker_demo python flask_rest/tests/test.py

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "netapp_docker_demo_flask_rest"
  env: "NetappDockerDemoFlaskRest-env"
  bucket_name: "elasticbeanstalk-ap-south-1-782007939849"
  bucket_path: "netapp_docker_demo_flask_rest"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
     secure: "$AWS_SECRET_KEY"
