sudo: required
services:
  - docker

before_install:
  - docker build -t kannan1985/netapp_docker_demo -f Dockerfile.dev .

script:
  - docker run kannan1985/netapp_docker_demo python flask_rest/tests/test.py
