version: '3'
services:
    movies_rest_api:
        build:
          context: .
          dockerfile: Dockerfile.Dev
        command: flask_rest/app.py
        volumes:
           - .:/usr/src/app
        ports:
           - "5000:5000"
        depends_on: 
          redis-server
    redis-server:
        image: redis
