version: '3'
services:
    movies_rest_api_test:
        build:
          context: flask_rest
          dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        command: ['python tests/test.py']
    redis-server:
        image: redis
