version: '3'
services:
    movies_rest_api_test:
        build:
          context: .
          dockerfile: Dockerfile.Dev
        volumes:
            - .:/usr/src/app
        command: ['flask_rest/tests/test.py']
    redis-server:
        image: redis
