version: '3'
services:
   directors_rest_api_test:
       build:
         context: .
         dockerfile: Dockerfile.dev
       volumes:
         - "./tests:/tests"
       command: ["python","/tests/test.py"]
